export type SinglePostType = {
    id: string,
    title: string,
    databaseId: number,
    content: string,
    date: string,
    modified: string,
    excerpt: string,
    slug: string,
    featuredImage: string,
    categoriesName: string,
    categoriesSlug: string,
    categoriesDatabaseId: string,
    authorName: string,
    authorSlug: string,
    authorDescription: string,
}